DROP DATABASE IF EXISTS YouGoGirl_db;
CREATE DATABASE YouGoGirl_db;

CREATE TABLE Users (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userName VARCHAR(10) NOT NULL,
email VARCHAR(50),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SavedAirports (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
location_name VARCHAR(10) NOT NULL,
risk_level INT (2) UNASIGNED AUTO_INCREMENT PRIMARY KEY,
quarantine_needed VARCHAR (10) NOT NULL,
date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);